apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260620-224611-dwqhd6wapnrs-service
spec:
  selector:
    app: enterprise-system-20260620-224611-dwqhd6wapnrs
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
